/**
 * Action types for bootcamp actions.
 */
export const GET_BOOTCAMP_REQUEST = 'GET_BOOTCAMP_REQUEST';
export const GET_BOOTCAMP_REQUEST_SUCCESS = 'GET_BOOTCAMP_REQUEST_SUCCESS';
export const GET_BOOTCAMP_REQUEST_FAILURE = 'GET_BOOTCAMP_REQUEST_FAILURE';
